from goprocam import GoProCamera, constants
import time 
time.sleep(10)
gpCam = GoProCamera.GoPro(constants.gpcontrol)
print('Set Photo Single Mode')
ret = gpCam.mode(constants.Mode.PhotoMode, constants.Mode.SubMode.Photo.Single)
print(ret)
time.sleep(2)
print('Set HDR ON')
ret = gpCam.gpControlSet(constants.Photo.SUPER_PHOTO, constants.Photo.SuperPhoto.HDROnly)
print(ret)
time.sleep(2)
print('Take Picture')
gpCam.take_photo()
time.sleep(5)
print('Download')
gpCam.downloadLastMedia()
time.sleep(10)

print('Set HDR OFF')
ret = gpCam.gpControlSet(constants.Photo.SUPER_PHOTO, constants.Photo.SuperPhoto.OFF)
print(ret)
time.sleep(2)
print('Take Picture')
gpCam.take_photo()
time.sleep(2)
print('Download')
gpCam.downloadLastMedia()

